(defun ssh-authorize ()
  (interactive)
  (end-of-buffer)
  (insert-string "cat <<EOF >>~/.ssh/authorized_keys")
  (comint-send-input)
  (insert-file-contents "~/.ssh/id_rsa.pub")
  (comint-send-input)
  (insert-string "EOF")
  (comint-send-input))

(autoload 'remote-edit-file "remote-edit" nil t)
(define-key ctl-x-map "F" 'remote-edit-file)
