from Node import Package,Module,Screen


elisp = Package(name = "Elisp",
                elements = [Module(name = "message-notify.el",
                                   description  = "Show alerts and notifications."),
                            Module(name = "idle-require.el",
                                   description  = "Instead of loading elisp packages " +
                                   "at start-up or on-demand, load them when Emacs is idle" +
                                   " for a longer period of time."),
                            ])

faces = Package(name = "VisualLook",
                elements = [Module(name = "fonts.el",
                                   description  = "configures fonts look"),
                            Module(name = "window.el",
                                   description = "emacs window look"),
                            Module(name = "general-highlight.el",
                                   description = "highlight text peaces"),
                            Module(name = "display-clock.el",
                                   description = "display clock"),
                            Module(name = "htmlfontify-init.el",
                                   description = "create html representation of the buffer"),
                            ])

navigation = Package(name = "Navigation",
                     elements = [Module(name = "init.el",
                                        description = "misc initializations"),
                                 Module(name = "dired-init.el",
                                        description = "initialize dired related stuff"),
                                 Module(name = "buffer-rotate.el",
                                        description = "provides rotation between buffers"),
                                 Module(name = "markers.el",
                                        description = "place markers inside barkers and jump between them"),
                                 Module(name = "buffer-manipulate.el",
                                        description = "basic operation on buffers such as close/change positions etc ..."),
                                 Module(name = "source-browse.el",
                                        description = "provides source code browsing support"),
                                 Module(name = "hide-show.el",
                                        description = "enable show hide support"),
                                 Module(name = "symbols-navigate.el",
                                        description = "navigate symbols with ido mode"),
                                 Package(name = "w3m",
                                         elements = [Module(name = "w3m-init.el",
                                                            description = "init w3m"),
                                                     ]),
                                 ])

macros = Package(name = "Macros",elements =
                 [Module(name = "init.el",
                         description = "basic macros operation record/replay etc ..."),
                  ])

shell = Package(name = "Shell",
                elements = [Module(name = "shell-buffer.el",
                                   description = "basic commands on shell buffer"),
                            Module(name = "eshell-conf.el",
                                   description = "eshell configurations"),
                            Module(name = "man-pages.el",
                                   description = "man and info pages"),
                            Module(name = "ssh-utils.el",
                                   description = "ssh utils"),
                            ])

editing = Package(name = "Editing",
                  elements = [Module(name = "init.el",
                                     description = "commong editing settings"),
                              Module(name = "dos2unix.el",
                                     description = "dos to unix and vice versa converions"),
                              Module(name = "rectangle.el",
                                     description = "Edit text rectangles in emacs"),
                              ])
publishing = Package(name = "Publishing",
                        elements = [Package(name = "org",
                                            elements = [Module(name = "org-init.el",
                                                               description = "init org mode"),
                                                        Package(name = "lisp",
                                                                elements = []),
                                                        Package(name = "contrib/lisp",
                                                                elements = []),
                                                        ]),
                                    Package(name = "auctex",
                                            elements = [Module(name = "auctex-init.el",
                                                               description = "init auctex mode"),
                                                        ]),
                                    Module(name = "artist-mode-init.el",
                                           description = "artist mode initialization"),
                                    ])


languages = Package(name = "Languages",
                    elements = [Module(name = "comments.el",
                                       description = "provides comments shortcuts for all programming languages modes"),
                                Module(name = "compiler.el",
                                       description = "compiler definitions"),
                                Module(name = "debug-ng.el",
                                       description = "debugging definitions"),
                                Module(name = "source-code.el",
                                       description = "general source code configuration"),
                                Package(name = "Documentation",
                                        elements = [Module(name = "init.el",
                                                           description = "initialize documentation modules"),
                                                    ]),
                                Package(name = "Templates",
                                        elements = [Module(name = "init.el",
                                                           description = "initialize templates"),
                                                    ]),
                                Package(name = "CC",
                                        elements = [Module(name = "init.el",
                                                           description = "init c/c++ mode"),
                                                    ]),
                                Package(name = "Java",
                                        elements = [Module(name = "init.el",
                                                           description = "init java mode"),
                                                    ]),
                                Package(name = "JavaScript",
                                        elements = [Module(name = "init.el",
                                                           description = "init java script mode"),
                                                    ]),
                                Package(name = "Lisp",
                                        elements = [Module(name = "scratch-buffer.el",
                                                           description = "prepare the scratch buffer"),
                                                    Module(name = "init.el",
                                                           description = "init lisp mode")]),
                                Package(name = "Perl",
                                        elements = [Module(name = "perl.el",
                                                           description = "perl mode"),
                                                    ]),
                                Package(name = "Clojure",
                                        elements = [Module(name = "init.el",
                                                           description = "clojure mode mode"),
                                                    ]),
                                Package(name = "Python",
                                        elements = [Module(name = "pdb.el",
                                                           description = "use pdb for python debugging"),
                                                    Module(name = "init.el",
                                                           description = "init python mode"),
                                                    ]),
                                Package(name = "Ruby",
                                        elements = [Module(name = "init.el",
                                                           description = "init ruby mode"),
                                                    ]),
                                Package(name = "Erlang",
                                        elements = [Module(name = "erlang-start.el",
                                                           description = "init erlang mode"),
                                                    ]),
                                Package(name = "Go",
                                        elements = [Module(name = "init.el",
                                                           description = "init go mode"),
                                                    ]),
                                Package(name = "Lua",
                                        elements = [Module(name = "lua-init.el",
                                                           description = "init lua mode"),
                                                    ]),
                                ])

build_system = Package(name = "BuildSystem",
                       elements = [Module(name = "init.el",
                                          description = "initialzie build system modes"),
                                   ])


source_control = Package(name = "SourceControl",
                         elements = [Module(name = "init.el",
                                            description = "load git/svn support"),
                                     Module(name = "local.el",
                                            description = "local files diff"),
                                     ])
applications = Package(name = "Applications",
                         elements = [Module(name = "init.el",
                                            description = "misc applications"),
                                     Module(name = "irc.el",
                                            description = "irc configration"),
                                     ])

packages = Package(name = "Packages",
                   elements = [Module(name = "init.el",
                                      description = "load elpa packages")
                               ])


PACKAGES = Package(name = ".",
                   elements = [elisp,
                               faces,
                               editing,
                               navigation,
                               macros,
                               shell,
                               publishing,
                               languages,
                               build_system,
                               source_control,
                               applications,
                               packages,
                               ])

SCREEN = Screen(x=0,
                y=26,
                height=51,
                width =159,
                font="-unknown-DejaVu Sans Mono-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1")
