; unicode character abbreviations, activated in emacs abbreviation mode
(define-abbrev-table 'global-abbrev-table '(
    ("forall" "∀" nil 0)
    ("mexists" "∃" nil 0)
    ("nots" "¬" nil 0)
    ("turnS" "⊦" nil 0)
    ("bottom" "⊥" nil 0)
    ("emptySet" "∅" nil 0)
    ("inSet" "∈" nil 0)
    ("inSetNot" "∉" nil 0)
    ("subSet" "⊆" nil 0)
    ("subSetS" "⊂" nil 0)
    ("subSetNot" "⊄" nil 0)
    ("sUnion" "⋃" nil 0)
    ("sInter" "⋂" nil 0)
    ("ar1" "→" nil 0)
    ("ar2" "⇒" nil 0)
    ("ar3" "↦" nil 0)
    ("uarrow" "↑" nil 0)
    ("darrow" "↓" nil 0)
    ("dArrow" "⇓" nil 0)
    ("cProd" "×" nil 0)
    ("alpha" "α" nil 0)
    ("beta" "β" nil 0)
    ("gamma" "γ" nil 0)
    ("Gamma" "Γ" nil 0)
    ("delta" "δ" nil 0)
    ("Delta" "Δ" nil 0)
    ("epsilon" "ε" nil 0)
    ("eta" "η" nil 0)
    ("theta" "θ" nil 0)
    ("Theta" "Θ" nil 0)
    ("zeta" "ζ" nil 0)
    ("kappa" "κ" nil 0)
    ("lambda" "λ" nil 0)
    ("Lambda" "Λ" nil 0)
    ("mu" "μ" nil 0)
    ("nu" "ν" nil 0)
    ("xsi" "ξ" nil 0)
    ("pi" "π" nil 0)
    ("Pi" "Π" nil 0)
    ("rho" "ρ" nil 0)
    ("sigma" "ς" nil 0)
    ("Sigma" "Σ" nil 0)
    ("tau" "τ" nil 0)
    ("upsilon" "υ" nil 0)
    ("Upsilon" "Υ" nil 0)
    ("phi" "φ" nil 0)
    ("Phi" "Φ" nil 0)
    ("psi" "ψ" nil 0)
    ("Psi" "Ψ" nil 0)
    ("omega" "ω" nil 0)
    ("Omega" "Ω" nil 0)
    ("Infinity" "∞" nil 0)
    ("neq" "≠" nil 0)
    ("dotOp" "•" 0)

    ))
(defun math-symbols ()
  (interactive)
  (abbrev-mode 1))
