(autoload 'package-list-packages "package" nil t)
(autoload 'package-list-packages-no-fetch "package" nil t)
(setq package-archives '(("ELPA" . "http://tromey.com/elpa/") 
                         ("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")))
